### ISSUE TITLE
Cannot build data-node 1.2.0

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/data-node#180]
### Problem description

Cannot build data-node 1.2.0

#### Steps to reproduce the issue
```
$ docker image ls
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
docker.io/hello-world   latest              d1165f221234        3 months ago        13.3 kB
[crdw@torres:~/data-node]$ dicker^C
[crdw@torres:~/data-node]$ docker-compose up --build
Pulling db (sagebionetworks/mongo:4.4.4)...
Trying to pull repository docker.io/sagebionetworks/mongo ...
4.4.4: Pulling from docker.io/sagebionetworks/mongo
92dc2a97ff99: Pull complete
be13a9d27eb8: Pull complete
c8299583700a: Pull complete
f61ed17142e4: Pull complete
bed7676d225b: Pull complete
ba553bcfc69c: Pull complete
e5046b6c236f: Pull complete
80191acfded2: Pull complete
d41d63fc76cc: Pull complete
5605b8c2e9f7: Pull complete
e8b16825b485: Pull complete
3d40ccce1309: Pull complete
b2a87f29aad6: Pull complete
b193b22ea01a: Pull complete
Digest: sha256:361fd558833d7468194f80c69f4d742ef808300c7a80271e4357467a28640453
Status: Downloaded newer image for docker.io/sagebionetworks/mongo:4.4.4
Building data-node
unknown flag: --iidfile
See 'docker build --help'.
ERROR: Service 'data-node' failed to build : Build failed
```
#### Expected behavior

- Build completes without error

**Comment by tschaffter** [comment]
@gkowalski What version of Docker and docker-compose are you using? I can successfully build the image with on

```
$ docker --version
Docker version 20.10.2, build 2291f61
```

Also, our documentation start to systematically recommend the use of `docker compose` instead of `docker-compose`. `docker compose` comes with the Docker Engine while `docker-compose` requires an extra package to be installed. This will be documented in the README of this repo soon (#175 ).

@gkowalski @thomasyu888 When deploying the data node, you should the production image stored on Docker Hub and not build it yourself. Note that I find the behavior of docker compose confusion regarding when it build the image or when it pull it from a registry when `image:` is defined in `docker-compose.yml`. The best approach I know is 1) delete any image of the data node if you have on locally, 2) `docker compose pull`, 3) `docker compose up`. This too will be added to the README later.

**Comment by gkowalski** [comment]
[crdw@torres:~/data-node]$ docker --version
Docker version 1.13.1, build 7d71120/1.13.1

**Comment by gkowalski** [comment]
Updated to latest https://docs.docker.com/engine/install/centos/#install-using-the-repository Docker . Does not come with "docker compose" , at least on CENTOS 7

**Comment by gkowalski** [comment]
donking now
